name: Eco-Seg
description: Eco-Seg, a pioneering waste segregation system
author: Cloudera Inc.
specification_version: 1.0
prototype_version: 1.0
date: "2024-02-16"

runtimes:
  - editor: JupyterLab
    kernel: Python 3.9.13
    edition: Nvidia GPU
